query Article($slug: String!) {
	articles(filters: {Slug: {eq: $slug}}){
        data{
            id
             attributes {
                Title
                Content { 
                    __typename 
                    ... on ComponentModuleText {
           		        Text
                    }
                }
	        }
        }
    }
}