query getArticlesByCat($slug: String!) {
  articles(filters: { category: { slug: { eq: $slug } } }, sort: "title:asc") {
    data {
      attributes {
        slug
        title
        category {
          data {
            attributes {
              name
            }
          }
        }
        type {
          data {
            attributes {
              slug
              name
            }
          }
        }
      }
    }
  }
}
