query getArticles {
  articles {
    data {
      attributes {
        slug
        abstract
        title
        content
        category {
          data {
            attributes {
              name
            }
          }
        }
        image {
          data {
            attributes {
              url
            }
          }
        }
      }
    }
  }
}
