query getArticles {
  articles(sort: "createdAt:desc", pagination: { limit: 11 }) {
    data {
      attributes {
        slug
        title
        content
        createdAt
        category {
          data {
            attributes {
              name
            }
          }
        }
        image {
          data {
            attributes {
              url
              caption
            }
          }
        }
      }
    }
  }
}
