query getCategories {
  categories {
    data {
        id
      attributes {
        name
        articles {
          data {
            attributes {
                slug
                title
            }
          }
        }
      }
    }
  }
}
